{% set version = "2.1.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ecodist
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ecodist_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ecodist/ecodist_{{ version }}.tar.gz
  sha256: e0a27ead727152d11b0093301983c1d88d7a3ee6a6396268e8581100baf43d98

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - libblas
    - r-base
    - r-igraph
  run:
    - r-base
    - r-igraph

test:
  commands:
    - $R -e "library('ecodist')"           # [not win]
    - "\"%R%\" -e \"library('ecodist')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ecodist
  dev_url: https://github.com/phiala/ecodist
  license: GPL-2.0-or-later
  summary: Dissimilarity-based analysis functions including ordination and Mantel test functions, intended for use with spatial and community data.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr

# Package: ecodist
# Version: 2.0.1
# Date: 2017-07-12
# Title: Dissimilarity-Based Functions for Ecological Analysis
# Authors@R: c(person("Sarah", "Goslee", role = c("aut", "cre"), email = "Sarah.Goslee@ars.usda.gov"), person("Dean", "Urban", role = "aut"))
# Author: Sarah Goslee [aut, cre], Dean Urban [aut]
# Maintainer: Sarah Goslee <Sarah.Goslee@ars.usda.gov>
# Depends: R (>= 3.0.0)
# LazyData: true
# Imports: stats, graphics
# Suggests: knitr, testthat
# VignetteBuilder: knitr
# Description: Dissimilarity-based analysis functions including ordination and Mantel test functions, intended for use with spatial and community data.
# License: GPL (>= 2)
# NeedsCompilation: yes
# Packaged: 2017-07-12 20:54:53 UTC; sarahg
# Repository: CRAN
# Date/Publication: 2017-07-13 05:25:44 UTC
