travis:
  secure:
    BINSTAR_TOKEN: pNVRTnrUnqSh0vn14kHgJWZ4dcOiNILEYhhXlUyaWVZgZMqrnebN+T2A4mvhk/1lryiHwLofUEjBWOHCUq/Mex05tFiA+sUJbsX1XN25mNyXXd73m/GrSdDN7vVC9YqbFBs1D3iMtg8pLq0v8sA/OviQdaXJFLS+mmmcSQ9fdwB9QwWZjidi+LEkpppo4pr0si7gHZuGoBpsy637XKAUhBkXnCyQYvkHVJmUg+LOfJw1CzAdjk75c0BqoGAZ4RJupzT8Bnl6Jh1rfwYLyyo6b99wXEwysElsmay7K9pPoayqmL7TGGzmnj7KiEU5RjcNJFoQLPxcwmRwTGZFq0BxS1NIkNbIujG0iNwtZCM1AcrNHH4dtuwr2bIRSKQpbaLqhb4+MU7UAGx27SmZ69t2zu7Y2kPqKaHgxE8TcF14YFdGETMD/Qyw0gSGiebPRNBVW70jlUyrVy9nU1WTkp9y1ayZfNtsgL3ZbM27z33m5PWvZZLWJLmCfJcjvZQHC54FRYkqrZsdUS3VoP+1t4+76e0sImOau9Oq0eyhOK6sgMdi9Tjf0cRiTGuHTMqZNEBrM2eFAqg/AVa8vYgj11y+5/Mn+kAFNIXG8ov7WTtmyCXdUk4n/EGZ5MDKTfVawoZRY4b68y4jPoVbdaFl7wLatFM8iB5jTPU+maJROzdEwMc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
